"""initial schema

Revision ID: d17215abc9ab
Revises: 
Create Date: 2026-09-30 03:40:34.919055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd17215abc9ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_users_email'))
    )
    op.create_table('click_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('type', sa.Enum('call', 'whatsapp', 'quote', 'email', name='click_type'), nullable=False),
    sa.Column('page', sa.String(length=300), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_click_events'))
    )
    op.create_index('ix_click_events_created_at_type', 'click_events', [sa.literal_column('created_at DESC'), 'type'], unique=False)
    op.create_table('enquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('project_type', sa.String(length=60), nullable=False),
    sa.Column('system_size', sa.String(length=60), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'quoted', 'won', 'lost', 'spam', name='enquiry_status'), server_default='new', nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('source_page', sa.String(length=300), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of'], ['enquiries.id'], name=op.f('fk_enquiries_duplicate_of_enquiries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enquiries'))
    )
    op.create_index('ix_enquiries_created_at', 'enquiries', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_enquiries_follow_up_date', 'enquiries', ['follow_up_date'], unique=False, postgresql_where=sa.text('follow_up_date IS NOT NULL'))
    op.create_index('ix_enquiries_phone_created_at', 'enquiries', ['phone', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_enquiries_project_type', 'enquiries', ['project_type'], unique=False)
    op.create_index('ix_enquiries_status_created_at', 'enquiries', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('fk_audit_log_admin_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_entity_created_at', 'audit_log', ['entity_type', 'entity_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('enquiry_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('fk_enquiry_notes_admin_id_admin_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], name=op.f('fk_enquiry_notes_enquiry_id_enquiries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enquiry_notes'))
    )
    op.create_index('ix_enquiry_notes_enquiry_id_created_at', 'enquiry_notes', ['enquiry_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enquiry_notes_enquiry_id_created_at', table_name='enquiry_notes')
    op.drop_table('enquiry_notes')
    op.drop_index('ix_audit_log_entity_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_enquiries_status_created_at', table_name='enquiries')
    op.drop_index('ix_enquiries_project_type', table_name='enquiries')
    op.drop_index('ix_enquiries_phone_created_at', table_name='enquiries')
    op.drop_index('ix_enquiries_follow_up_date', table_name='enquiries', postgresql_where=sa.text('follow_up_date IS NOT NULL'))
    op.drop_index('ix_enquiries_created_at', table_name='enquiries')
    op.drop_table('enquiries')
    op.drop_index('ix_click_events_created_at_type', table_name='click_events')
    op.drop_table('click_events')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
    sa.Enum(name='enquiry_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='click_type').drop(op.get_bind(), checkfirst=True)
